---
title: "Datos policiales"
author: "Joselin Guido"
date: '2022-06-21'
output: 
  html_document:
    code_folding: hide 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



 
```{r paquetes, message=FALSE}
#Pasos cargar paquetes de R en un segmento de código
library(DT)
library(ggplot2)
library(plotly)
library(dplyr)
library(leaflet)
library(sf)
library(readxl)
library(tidyverse)
library(ggthemes)

```
 

#Proyecto 2
```{r}
Estadisticas_Policiales <- 
  readxl::read_excel("estadisticaspoliciales2021.xls")

Estadisticas_Policiales$Fecha <- as.Date(Estadisticas_Policiales$Fecha, format = "%Y-%m-%d")
```

# Tabla de variables

```{r, message=FALSE}
# Tabla interactiva del paquete DT

Estadisticas_Policiales %>%
  dplyr::select(Delito,
                Fecha,
                Victima,
                Edad,
                Genero,
                Provincia,
                Canton) %>%
  mutate(Fecha = as.Date(Fecha, format = "%d/%m/%Y")) %>%
  datatable(
    options = list(
      pageLength = 15,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    ),
    colnames = c(
      # encabezados de las columnas
      "Delito",
      "Fecha",
      "Víctima",
      "Edad",
      "Género",
      "Provincia",
      "Cantón"
    )
  )
```
# Gráfico de Cantidad de delitos por tipo de delito

```{r}
Cantidad_de_delito_por_tipo <-
  Estadisticas_Policiales %>%
  count(Delito) %>%
  ggplot(aes(x = reorder(Delito, n), y = n)) +
  geom_bar(stat = "identity") +
  ggtitle("Cantidad de delitos por tipo de delito") +
  xlab("Tipo de Delito") +
  ylab("Cantidad") +
  coord_flip() +
  theme_hc()

Cantidad_de_delito_por_tipo %>%
  ggplotly() %>%
  config(locale = "es")
```
# Gráfico de cantidad de delitos por mes del año


# Gráfico de Delitos por Género

```{r}
Proporcion_de_Delito_por_Genero <-
  Estadisticas_Policiales %>%
  ggplot(aes(x = Genero, fill = Delito)) +
  geom_bar(position = "fill") +
  ggtitle("Proporciones de Delito por tipo de Género") +
  xlab("Género") +
  ylab("Proporción") +
  labs(fill = "Delito") +
  theme_minimal()

ggplotly(Proporcion_de_Delito_por_Genero) %>% config(locale = 'es')
```

#Gráfico de cantidad de delitos provincias

```{r}
grafico <- filter(Estadisticas_Policiales, grepl('SAN JOSE|ALAJUELA|HEREDIA|CARTAGO', Provincia))

Delitos_SanJose_Alajuela_Cartago_Heredia <-
  ggplot(data= grafico, aes(x=Provincia)) +
  geom_bar( ) +
  ggtitle("Delitos por provincia") +
  xlab("Provincias") +
  ylab("Cantidad de Delitos") +
  theme_minimal()

ggplotly(Delitos_SanJose_Alajuela_Cartago_Heredia) %>% config(locale = 'es')
```




